git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --true-color=always
gui:
  border: rounded
  nerdFontsVersion: "3"
  showBottomLine: false
  showIcons: true
  theme:
    selectedLineBgColor:
      - reverse
keybinding:
  universal:
    optionMenu: '?'
    optionMenu-alt1: '?'
notARepository: quit
os:
  editPreset: nvim-remote
